module.exports = {
	COMMUNITY_CHAT:"COMMUNITY_CHAT",
	USER_CONNECTED:"USER_CONNECTED",
	MESSAGE_RECIEVED:"MESSAGE_RECIEVED",
	MESSAGE_SENT:"MESSAGE_SENT",
	USER_DISCONNECTED:"USER_DISCONNECTED",
	TYPING:"TYPING",
	VERIFY_USER:"VERIFY_USER",
	LOGOUT:"LOGOUT",
	CONNECTED_LIST:"CONNECTED_LIST",
	MESSAGES_SENT: "MESSAGES_SENT",
	MESSAGE_PRIVATE:"MESSAGE_PRIVATE",
	USER_START:"USER_START",
	INVITE:"INVITE",
	INVITE_RECEIVED:"INVITE_RECEIVED",
	MESSAGE_PRIVATE:"MESSAGE_PRIVATE"
}
